# Generated by Django 5.2.17 on 2026-08-17 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='Proveedor.proveedor'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='Proveedor.proveedor'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
