# Generated by Django 5.2.17 on 2026-08-17 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0001_initial'),
        ('inventario', '0002_alter_producto_proveedor_alter_movimiento_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='Categoria.categoria'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
