# Generated by Django 5.2.17 on 2026-08-17 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
        ('inventario', '0003_alter_producto_categoria_delete_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='Cliente.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
