# Generated by Django 5.2.17 on 2026-08-17 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
        ('inventario', '0004_alter_movimiento_cliente_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_movimiento', to='Producto.producto'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
