# Generated by Django 5.2.17 on 2026-08-17 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_detallemovimiento_producto_delete_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DetalleMovimiento',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
